name: Format

on:
  workflow_call:

jobs:
  format:
    name: Format check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Node & Yarn
        uses: collide-kit/collide-wfls/actions/prepare@187af17a654548eb073d2aae86ee2e095c546950 # v1.0.0

      - name: Run format check
        run: yarn fmt:check
