name: Test

on:
  workflow_call:

jobs:
  test:
    name: Validate config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node & Yarn
        uses: collide-kit/collide-wfls/actions/prepare@187af17a654548eb073d2aae86ee2e095c546950 # v1.0.0

      - name: Run config validation
        run: yarn test
